### PR TITLE
PLATML-4285 python, scala scoringResultsDataSetId

### PR DESCRIPTION
**Pull request by shivmpatel12**
- change to output dataset configs to scoringResultsDataSetId
- remove hardcoded schemas and dataset ids
- use client_id passed in config from service for scala

### CODE REVIEW

**Review by jonaphin — COMMENTED** [review]
should we really remove ACP_DSW_TRAINING_XDM_SCHEMA ?

**Review by tumulurik — APPROVED** [review]
LGTM!

**Review by sathyarun18 — APPROVED** [review]
lgtm

**Comment by shivmpatel12** [comment]
@jonaphin What is the benefit of having it, especially if it's hardcoded to a specific org? My opinion is that it would just cause confusion. Now that the UI workflow has users to choose the schema, I don't think it should be in the config.

**Comment by jonaphin** [comment]
@shivmpatel12 I see your point. This being a sample I feel we should expose the framework-bound parameters. Many scientists will not go through the UI and exclusively use APIs... taking it offline with you

**Comment by shivmpatel12** [comment]
Discussed with @jonaphin. Will have schemas in config with value `"<leave as is if going through UI workflow. Replace with Schema ID if creating recipe via API>"`

**Review by jonaphin — APPROVED** [review]
beautiful

**Review by tumulurik — APPROVED** [review]
LGTM!

**Pull request merged**
