### PR TITLE
PLATML-1918 - Made changes to support default regression algorithm

### PR DESCRIPTION
**Pull request by NemanjaL94**

### CODE REVIEW

**Review by sathyarun18 — APPROVED** [review]
LGTM

**Review by tumulurik — COMMENTED** [review]
Nemanja, the recipe code looks good.
Have a question about the model-authoring-sdk changes which are going along with this PR, how are you referring to those changes from here?

**Comment by NemanjaL94** [comment]
@sathyarun18 @tumulurik 
I was using snapshot version of authoring sdk in order to test these changes and I didn't want to include snapshot version in PR review. I'm planning to release authoring sdk once I get approve from both of you, as retail sales currently uses authoring sdk 0.16.1 and the newest one that will be released is 0.19.1.
I'll update pom file here after I release authoring-sdk to central repository.

**Review by tumulurik — APPROVED** [review]
LGTM

**Pull request merged**
